### ISSUE TITLE
load aframe library from dependencies instead of from the web

### ISSUE THREAD

**Issue by thescientist13** [Aimeelr08/vr-demo-boilerplate#1]
Currently the **aframe** library is being loaded from the web.  With `npm` being used by the project, an alternative approach would be to use the version of **aframe** installed when instructed to run `npm install`.

The main advantage being that if an internet connection is not available, the app would still load.  Also, it couples the dependency referenced in _index.html_ to the project's manifest (_package.json_).

This pattern could also be used to load any other dependencies (like React)

**Comment by thescientist13** [comment]
Another good idea is to commit _package-lock.json_ so future `npm install` commands when run will be deterministic for all users.

**Comment by Aimeelr08** [comment]
🙌🏼👍
